-- MySQL Script generated by MySQL Workbench
-- 12/08/14 07:31:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema beraudent
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `beraudent` ;

-- -----------------------------------------------------
-- Schema beraudent
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `beraudent` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `beraudent` ;

-- -----------------------------------------------------
-- Table `beraudent`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beraudent`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `beraudent`.`Cliente` (
  `id_clie` INT NOT NULL AUTO_INCREMENT,
  `nomb_clie` VARCHAR(25) NOT NULL,
  `razo_clie` VARCHAR(45) NULL,
  `rut_clie` VARCHAR(10) NULL,
  `mail_clie` VARCHAR(30) NULL,
  `celu_clie` INT NULL,
  `asi1_clie` VARCHAR(45) NULL,
  `asi2_clie` VARCHAR(45) NULL,
  `exel_clie` ENUM('P','N','E') NULL,
  `envi_clie` ENUM('E','I','EI','CH') NULL,
  PRIMARY KEY (`id_clie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beraudent`.`Arancel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beraudent`.`Arancel` ;

CREATE TABLE IF NOT EXISTS `beraudent`.`Arancel` (
  `id_aran` INT NOT NULL,
  `nomb_aran` VARCHAR(20) NULL,
  PRIMARY KEY (`id_aran`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beraudent`.`Datos_Facturacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beraudent`.`Datos_Facturacion` ;

CREATE TABLE IF NOT EXISTS `beraudent`.`Datos_Facturacion` (
  `id_dato_fact` INT NOT NULL AUTO_INCREMENT,
  `razo_dato_fact` VARCHAR(45) NULL,
  `dire_dato_fact` VARCHAR(45) NULL,
  `rut_dato_fact` VARCHAR(45) NULL,
  `iva_dato_fact` ENUM('1','0') NULL,
  `deta_dato_fact` VARCHAR(45) NULL,
  PRIMARY KEY (`id_dato_fact`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beraudent`.`Ubicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beraudent`.`Ubicacion` ;

CREATE TABLE IF NOT EXISTS `beraudent`.`Ubicacion` (
  `id_ubic` INT NOT NULL AUTO_INCREMENT,
  `dire_ubic` VARCHAR(20) NOT NULL,
  `tipo_dire` CHAR(2) NULL,
  `depa_ubic` VARCHAR(5) NULL,
  `comu_ubic` VARCHAR(15) NULL,
  `regi_ubic` VARCHAR(45) NULL,
  `tel1_ubic` VARCHAR(45) NULL,
  `tel2_ubic` VARCHAR(45) NULL,
  PRIMARY KEY (`id_ubic`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beraudent`.`Sucursal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beraudent`.`Sucursal` ;

CREATE TABLE IF NOT EXISTS `beraudent`.`Sucursal` (
  `id_sucu` INT NOT NULL AUTO_INCREMENT,
  `nomb_sucu` VARCHAR(25) NOT NULL,
  `dire_sucu` VARCHAR(45) NOT NULL,
  `comu_sucu` VARCHAR(15) NULL,
  `regi_sucu` VARCHAR(15) NULL,
  `tel1_sucu` VARCHAR(10) NULL,
  `tel2_sucu` VARCHAR(10) NULL,
  `Arancel_id_aran` INT NOT NULL,
  `Cliente_id_clie` INT NOT NULL,
  `Datos_Facturacion_id_dato_fact` INT NOT NULL,
  `Ubicacion_id_ubic` INT NOT NULL,
  PRIMARY KEY (`id_sucu`),
  INDEX `fk_Sucursal_Arancel1_idx` (`Arancel_id_aran` ASC),
  INDEX `fk_Sucursal_Cliente1_idx` (`Cliente_id_clie` ASC),
  INDEX `fk_Sucursal_Datos_Facturacion1_idx` (`Datos_Facturacion_id_dato_fact` ASC),
  INDEX `fk_Sucursal_Ubicacion1_idx` (`Ubicacion_id_ubic` ASC),
  CONSTRAINT `fk_Sucursal_Arancel1`
    FOREIGN KEY (`Arancel_id_aran`)
    REFERENCES `beraudent`.`Arancel` (`id_aran`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sucursal_Cliente1`
    FOREIGN KEY (`Cliente_id_clie`)
    REFERENCES `beraudent`.`Cliente` (`id_clie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sucursal_Datos_Facturacion1`
    FOREIGN KEY (`Datos_Facturacion_id_dato_fact`)
    REFERENCES `beraudent`.`Datos_Facturacion` (`id_dato_fact`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sucursal_Ubicacion1`
    FOREIGN KEY (`Ubicacion_id_ubic`)
    REFERENCES `beraudent`.`Ubicacion` (`id_ubic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beraudent`.`Odontologo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beraudent`.`Odontologo` ;

CREATE TABLE IF NOT EXISTS `beraudent`.`Odontologo` (
  `id_odon` INT NOT NULL AUTO_INCREMENT,
  `apel_odon` VARCHAR(45) NULL,
  `nomb_odon` VARCHAR(45) NULL,
  `mail_odon` VARCHAR(25) NULL,
  `celu_odon` VARCHAR(10) NULL,
  PRIMARY KEY (`id_odon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beraudent`.`Administrativo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beraudent`.`Administrativo` ;

CREATE TABLE IF NOT EXISTS `beraudent`.`Administrativo` (
  `id_admi` INT NOT NULL AUTO_INCREMENT,
  `nomb_admi` VARCHAR(35) NULL,
  `apel_admi` VARCHAR(35) NULL,
  `mail_admi` VARCHAR(35) NULL,
  `celu_admi` VARCHAR(10) NULL,
  `carg_admi` VARCHAR(15) NULL,
  `tele_admi` VARCHAR(10) NULL,
  `Cliente_id_clie` INT NOT NULL,
  PRIMARY KEY (`id_admi`, `Cliente_id_clie`),
  INDEX `fk_Administrativo_Cliente1_idx` (`Cliente_id_clie` ASC),
  CONSTRAINT `fk_Administrativo_Cliente1`
    FOREIGN KEY (`Cliente_id_clie`)
    REFERENCES `beraudent`.`Cliente` (`id_clie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beraudent`.`Tipo_trabajo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beraudent`.`Tipo_trabajo` ;

CREATE TABLE IF NOT EXISTS `beraudent`.`Tipo_trabajo` (
  `idTipo_trabajo` INT NOT NULL,
  PRIMARY KEY (`idTipo_trabajo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beraudent`.`Trabajo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beraudent`.`Trabajo` ;

CREATE TABLE IF NOT EXISTS `beraudent`.`Trabajo` (
  `id_trab` INT NOT NULL,
  `Tipo_trabajo_idTipo_trabajo` INT NOT NULL,
  `Trabajo_id_trab` INT NOT NULL,
  PRIMARY KEY (`id_trab`),
  INDEX `fk_Trabajo_Tipo_trabajo1_idx` (`Tipo_trabajo_idTipo_trabajo` ASC),
  INDEX `fk_Trabajo_Trabajo1_idx` (`Trabajo_id_trab` ASC),
  CONSTRAINT `fk_Trabajo_Tipo_trabajo1`
    FOREIGN KEY (`Tipo_trabajo_idTipo_trabajo`)
    REFERENCES `beraudent`.`Tipo_trabajo` (`idTipo_trabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trabajo_Trabajo1`
    FOREIGN KEY (`Trabajo_id_trab`)
    REFERENCES `beraudent`.`Trabajo` (`id_trab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beraudent`.`Arancel_has_Trabajo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beraudent`.`Arancel_has_Trabajo` ;

CREATE TABLE IF NOT EXISTS `beraudent`.`Arancel_has_Trabajo` (
  `Arancel_id_aran` INT NOT NULL,
  `Trabajo_id_trab` INT NOT NULL,
  `prec_aran` INT NULL,
  PRIMARY KEY (`Arancel_id_aran`, `Trabajo_id_trab`),
  INDEX `fk_Arancel_has_Trabajo_Trabajo1_idx` (`Trabajo_id_trab` ASC),
  CONSTRAINT `fk_Arancel_has_Trabajo_Trabajo1`
    FOREIGN KEY (`Trabajo_id_trab`)
    REFERENCES `beraudent`.`Trabajo` (`id_trab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beraudent`.`Sucursal_Odontologo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beraudent`.`Sucursal_Odontologo` ;

CREATE TABLE IF NOT EXISTS `beraudent`.`Sucursal_Odontologo` (
  `Sucursal_id_sucu` INT NOT NULL,
  `Odontologo_id_odon` INT NOT NULL,
  PRIMARY KEY (`Sucursal_id_sucu`, `Odontologo_id_odon`),
  INDEX `fk_Sucursal_has_Doctor_Sucursal1_idx` (`Sucursal_id_sucu` ASC),
  INDEX `fk_Sucursal_Odontologo_Odontologo1_idx` (`Odontologo_id_odon` ASC),
  CONSTRAINT `fk_Sucursal_has_Doctor_Sucursal1`
    FOREIGN KEY (`Sucursal_id_sucu`)
    REFERENCES `beraudent`.`Sucursal` (`id_sucu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sucursal_Odontologo_Odontologo1`
    FOREIGN KEY (`Odontologo_id_odon`)
    REFERENCES `beraudent`.`Odontologo` (`id_odon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beraudent`.`Personal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beraudent`.`Personal` ;

CREATE TABLE IF NOT EXISTS `beraudent`.`Personal` (
  `id_pers` INT NOT NULL AUTO_INCREMENT,
  `nomb_pers` VARCHAR(35) NULL,
  `apel_pers` VARCHAR(35) NULL,
  `mail_pers` VARCHAR(35) NULL,
  `celu_pers` VARCHAR(10) NULL,
  `carg_pers` VARCHAR(15) NULL,
  `tele_pers` VARCHAR(45) NULL,
  `Sucursal_id_sucu` INT NOT NULL,
  PRIMARY KEY (`id_pers`, `Sucursal_id_sucu`),
  INDEX `fk_Personal_Sucursal1_idx` (`Sucursal_id_sucu` ASC),
  CONSTRAINT `fk_Personal_Sucursal1`
    FOREIGN KEY (`Sucursal_id_sucu`)
    REFERENCES `beraudent`.`Sucursal` (`id_sucu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beraudent`.`Orden_Trabajo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beraudent`.`Orden_Trabajo` ;

CREATE TABLE IF NOT EXISTS `beraudent`.`Orden_Trabajo` (
  `num_orde_trab` INT NOT NULL,
  `ot_orde_trab` VARCHAR(10) NULL,
  `tick_orde_trab` VARCHAR(10) NULL,
  `fech_ingr` DATETIME NULL,
  `fech_entr` DATETIME NULL,
  PRIMARY KEY (`num_orde_trab`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beraudent`.`Paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beraudent`.`Paciente` ;

CREATE TABLE IF NOT EXISTS `beraudent`.`Paciente` (
  `id_paciente` VARCHAR(45) NOT NULL,
  `rut_paciente` VARCHAR(10) NULL,
  `nomb_paciente` VARCHAR(45) NULL,
  `apel_paciente` VARCHAR(45) NULL,
  PRIMARY KEY (`id_paciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beraudent`.`Orden_Pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beraudent`.`Orden_Pago` ;

CREATE TABLE IF NOT EXISTS `beraudent`.`Orden_Pago` (
  `id_orde_pago` INT NOT NULL,
  `nume_orde_pago` VARCHAR(10) NOT NULL,
  `mes_orde_pago` VARCHAR(10) NULL,
  `mont_orde_pago` FLOAT NULL,
  `deta_orde_pago` VARCHAR(45) NULL,
  PRIMARY KEY (`id_orde_pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beraudent`.`Orden_Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beraudent`.`Orden_Pedido` ;

CREATE TABLE IF NOT EXISTS `beraudent`.`Orden_Pedido` (
  `num_orde_pedi` VARCHAR(10) NOT NULL,
  `epi_orde_pedi` VARCHAR(10) NOT NULL,
  `fech_orde_pedi` VARCHAR(45) NOT NULL,
  `Sucursal_Odontologo_Sucursal_id_sucu` INT NOT NULL,
  `Sucursal_Odontologo_Odontologo_id_odon` INT NOT NULL,
  `Paciente_id_paciente` VARCHAR(45) NOT NULL,
  `Orden_Facturacion_id_orde_fact` INT NOT NULL,
  PRIMARY KEY (`num_orde_pedi`),
  INDEX `fk_Pedido_Sucursal_Odontologo1_idx` (`Sucursal_Odontologo_Sucursal_id_sucu` ASC, `Sucursal_Odontologo_Odontologo_id_odon` ASC),
  INDEX `fk_Pedido_Paciente1_idx` (`Paciente_id_paciente` ASC),
  INDEX `fk_Orden_Pedido_Orden_Facturacion1_idx` (`Orden_Facturacion_id_orde_fact` ASC),
  CONSTRAINT `fk_Pedido_Sucursal_Odontologo1`
    FOREIGN KEY (`Sucursal_Odontologo_Sucursal_id_sucu` , `Sucursal_Odontologo_Odontologo_id_odon`)
    REFERENCES `beraudent`.`Sucursal_Odontologo` (`Sucursal_id_sucu` , `Odontologo_id_odon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Paciente1`
    FOREIGN KEY (`Paciente_id_paciente`)
    REFERENCES `beraudent`.`Paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orden_Pedido_Orden_Facturacion1`
    FOREIGN KEY (`Orden_Facturacion_id_orde_fact`)
    REFERENCES `beraudent`.`Orden_Pago` (`id_orde_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beraudent`.`Arancel_Trabajo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beraudent`.`Arancel_Trabajo` ;

CREATE TABLE IF NOT EXISTS `beraudent`.`Arancel_Trabajo` (
  `Trabajo_id_trab` INT NOT NULL,
  `Arancel_id_aran` INT NOT NULL,
  `precio` FLOAT NOT NULL,
  PRIMARY KEY (`Trabajo_id_trab`, `Arancel_id_aran`),
  INDEX `fk_Arancel_Trabajo_Arancel1_idx` (`Arancel_id_aran` ASC),
  CONSTRAINT `fk_Arancel_Trabajo_Trabajo1`
    FOREIGN KEY (`Trabajo_id_trab`)
    REFERENCES `beraudent`.`Trabajo` (`id_trab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Arancel_Trabajo_Arancel1`
    FOREIGN KEY (`Arancel_id_aran`)
    REFERENCES `beraudent`.`Arancel` (`id_aran`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beraudent`.`Excepcion_Arancel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beraudent`.`Excepcion_Arancel` ;

CREATE TABLE IF NOT EXISTS `beraudent`.`Excepcion_Arancel` (
  `Sucursal_id_sucu` INT NOT NULL,
  `Arancel_Trabajo_Trabajo_id_trab` INT NOT NULL,
  `Arancel_Trabajo_Arancel_id_aran` INT NOT NULL,
  `precio_excepcion` FLOAT NOT NULL,
  PRIMARY KEY (`Sucursal_id_sucu`, `Arancel_Trabajo_Trabajo_id_trab`, `Arancel_Trabajo_Arancel_id_aran`),
  INDEX `fk_Excepcion_Arancel_Arancel_Trabajo1_idx` (`Arancel_Trabajo_Trabajo_id_trab` ASC, `Arancel_Trabajo_Arancel_id_aran` ASC),
  CONSTRAINT `fk_Excepcion_Arancel_Sucursal1`
    FOREIGN KEY (`Sucursal_id_sucu`)
    REFERENCES `beraudent`.`Sucursal` (`id_sucu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Excepcion_Arancel_Arancel_Trabajo1`
    FOREIGN KEY (`Arancel_Trabajo_Trabajo_id_trab` , `Arancel_Trabajo_Arancel_id_aran`)
    REFERENCES `beraudent`.`Arancel_Trabajo` (`Trabajo_id_trab` , `Arancel_id_aran`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beraudent`.`Trabajo_Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beraudent`.`Trabajo_Pedido` ;

CREATE TABLE IF NOT EXISTS `beraudent`.`Trabajo_Pedido` (
  `Arancel_Trabajo_Trabajo_id_trab` INT NOT NULL,
  `Arancel_Trabajo_Arancel_id_aran` INT NOT NULL,
  `Pedido_num_pedido` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Arancel_Trabajo_Trabajo_id_trab`, `Arancel_Trabajo_Arancel_id_aran`, `Pedido_num_pedido`),
  INDEX `fk_Arancel_Trabajo_has_Pedido_Pedido1_idx` (`Pedido_num_pedido` ASC),
  INDEX `fk_Arancel_Trabajo_has_Pedido_Arancel_Trabajo1_idx` (`Arancel_Trabajo_Trabajo_id_trab` ASC, `Arancel_Trabajo_Arancel_id_aran` ASC),
  CONSTRAINT `fk_Arancel_Trabajo_has_Pedido_Arancel_Trabajo1`
    FOREIGN KEY (`Arancel_Trabajo_Trabajo_id_trab` , `Arancel_Trabajo_Arancel_id_aran`)
    REFERENCES `beraudent`.`Arancel_Trabajo` (`Trabajo_id_trab` , `Arancel_id_aran`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Arancel_Trabajo_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_num_pedido`)
    REFERENCES `beraudent`.`Orden_Pedido` (`num_orde_pedi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beraudent`.`Trabajo_Pedido_has_Orden_Trabajo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beraudent`.`Trabajo_Pedido_has_Orden_Trabajo` ;

CREATE TABLE IF NOT EXISTS `beraudent`.`Trabajo_Pedido_has_Orden_Trabajo` (
  `Trabajo_Pedido_Arancel_Trabajo_Trabajo_id_trab` INT NOT NULL,
  `Trabajo_Pedido_Arancel_Trabajo_Arancel_id_aran` INT NOT NULL,
  `Trabajo_Pedido_Pedido_num_pedido` VARCHAR(10) NOT NULL,
  `Orden_Trabajo_num_orde_trab` INT NOT NULL,
  PRIMARY KEY (`Trabajo_Pedido_Arancel_Trabajo_Trabajo_id_trab`, `Trabajo_Pedido_Arancel_Trabajo_Arancel_id_aran`, `Trabajo_Pedido_Pedido_num_pedido`, `Orden_Trabajo_num_orde_trab`),
  INDEX `fk_Trabajo_Pedido_has_Orden_Trabajo_Orden_Trabajo1_idx` (`Orden_Trabajo_num_orde_trab` ASC),
  INDEX `fk_Trabajo_Pedido_has_Orden_Trabajo_Trabajo_Pedido1_idx` (`Trabajo_Pedido_Arancel_Trabajo_Trabajo_id_trab` ASC, `Trabajo_Pedido_Arancel_Trabajo_Arancel_id_aran` ASC, `Trabajo_Pedido_Pedido_num_pedido` ASC),
  CONSTRAINT `fk_Trabajo_Pedido_has_Orden_Trabajo_Trabajo_Pedido1`
    FOREIGN KEY (`Trabajo_Pedido_Arancel_Trabajo_Trabajo_id_trab` , `Trabajo_Pedido_Arancel_Trabajo_Arancel_id_aran` , `Trabajo_Pedido_Pedido_num_pedido`)
    REFERENCES `beraudent`.`Trabajo_Pedido` (`Arancel_Trabajo_Trabajo_id_trab` , `Arancel_Trabajo_Arancel_id_aran` , `Pedido_num_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trabajo_Pedido_has_Orden_Trabajo_Orden_Trabajo1`
    FOREIGN KEY (`Orden_Trabajo_num_orde_trab`)
    REFERENCES `beraudent`.`Orden_Trabajo` (`num_orde_trab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beraudent`.`Comprobante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beraudent`.`Comprobante` ;

CREATE TABLE IF NOT EXISTS `beraudent`.`Comprobante` (
  `nume_comp` INT NOT NULL,
  `deta_comp` VARCHAR(45) NULL,
  `fech_comp` VARCHAR(45) NOT NULL,
  `tipo_comp` ENUM('F','B') NULL,
  `Sucursal_id_sucu` INT NOT NULL,
  `Orden_Pago_id_orde_pago` INT NOT NULL,
  PRIMARY KEY (`nume_comp`),
  INDEX `fk_Factura_Sucursal1_idx` (`Sucursal_id_sucu` ASC),
  INDEX `fk_Comprobante_Orden_Pago1_idx` (`Orden_Pago_id_orde_pago` ASC),
  CONSTRAINT `fk_Factura_Sucursal1`
    FOREIGN KEY (`Sucursal_id_sucu`)
    REFERENCES `beraudent`.`Sucursal` (`id_sucu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comprobante_Orden_Pago1`
    FOREIGN KEY (`Orden_Pago_id_orde_pago`)
    REFERENCES `beraudent`.`Orden_Pago` (`id_orde_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beraudent`.`Abono_Cargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beraudent`.`Abono_Cargo` ;

CREATE TABLE IF NOT EXISTS `beraudent`.`Abono_Cargo` (
  `id_abon_carg` INT NOT NULL,
  `deta_abon_carg` VARCHAR(45) NULL,
  `Trabajo_Pedido_Arancel_Trabajo_Trabajo_id_trab` INT NOT NULL,
  `Trabajo_Pedido_Arancel_Trabajo_Arancel_id_aran` INT NOT NULL,
  `Trabajo_Pedido_Pedido_num_pedido` VARCHAR(10) NOT NULL,
  `Orden_Facturacion_id_orde_fact` INT NOT NULL,
  PRIMARY KEY (`id_abon_carg`),
  INDEX `fk_Abono_Cargo_Trabajo_Pedido1_idx` (`Trabajo_Pedido_Arancel_Trabajo_Trabajo_id_trab` ASC, `Trabajo_Pedido_Arancel_Trabajo_Arancel_id_aran` ASC, `Trabajo_Pedido_Pedido_num_pedido` ASC),
  INDEX `fk_Abono_Cargo_Orden_Facturacion1_idx` (`Orden_Facturacion_id_orde_fact` ASC),
  CONSTRAINT `fk_Abono_Cargo_Trabajo_Pedido1`
    FOREIGN KEY (`Trabajo_Pedido_Arancel_Trabajo_Trabajo_id_trab` , `Trabajo_Pedido_Arancel_Trabajo_Arancel_id_aran` , `Trabajo_Pedido_Pedido_num_pedido`)
    REFERENCES `beraudent`.`Trabajo_Pedido` (`Arancel_Trabajo_Trabajo_id_trab` , `Arancel_Trabajo_Arancel_id_aran` , `Pedido_num_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Abono_Cargo_Orden_Facturacion1`
    FOREIGN KEY (`Orden_Facturacion_id_orde_fact`)
    REFERENCES `beraudent`.`Orden_Pago` (`id_orde_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beraudent`.`Recibo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beraudent`.`Recibo` ;

CREATE TABLE IF NOT EXISTS `beraudent`.`Recibo` (
  `nume_reci` INT NOT NULL,
  `fech_reci` DATETIME NULL,
  `deta_reci` VARCHAR(45) NULL,
  PRIMARY KEY (`nume_reci`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beraudent`.`Pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beraudent`.`Pagos` ;

CREATE TABLE IF NOT EXISTS `beraudent`.`Pagos` (
  `id_pago` INT NOT NULL,
  `tipo_pago` ENUM('E','T','R','W','D') NULL,
  `num_pago` VARCHAR(20) NULL,
  `fech_pago` DATETIME NULL,
  `banc_pago` VARCHAR(45) NULL,
  `deta_pago` VARCHAR(45) NULL,
  `Orden_Pago_id_orde_pago` INT NOT NULL,
  `Recibo_nume_reci` INT NOT NULL,
  PRIMARY KEY (`id_pago`),
  INDEX `fk_Pagos_Orden_Pago1_idx` (`Orden_Pago_id_orde_pago` ASC),
  INDEX `fk_Pagos_Recibo1_idx` (`Recibo_nume_reci` ASC),
  CONSTRAINT `fk_Pagos_Orden_Pago1`
    FOREIGN KEY (`Orden_Pago_id_orde_pago`)
    REFERENCES `beraudent`.`Orden_Pago` (`id_orde_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pagos_Recibo1`
    FOREIGN KEY (`Recibo_nume_reci`)
    REFERENCES `beraudent`.`Recibo` (`nume_reci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
