--192.168.0.13 PARA OBTENER LAS GUOIAS
SELECT * FROM [dbo].[GUIAS_E] where FolioNum='23177081'

--#############################################################################--
--###########  PARA DETENER ACTIVIDAD EN TIENDAS DURANTE INVENTARIO ###########--
--#############################################################################--


SELECT T1.U_GSP_FILWAREHOUSE AS code, T1.U_GSP_DESC AS name, T1.U_GSP_AUTOEXEC AS status, T2.U_GSP_TIPOINTEGRCP AS sync, T2.U_GSP_TIPOINTEGR, CONVERT(VARCHAR(10),T1.U_GSP_DATEMOD) AS date
FROM [@GSP_TPVWCD] AS T1 
INNER JOIN [@GSP_TPVSHOP] AS T2 ON T1.U_GSP_FILWAREHOUSE=T2.U_GSP_SHOP 
INNER JOIN OWHS AS T3 ON  T1.U_GSP_FILWAREHOUSE=T3.WhsCode
WHERE T3.U_GSP_SENDTPV='Y'
ORDER BY T1.U_GSP_FILWAREHOUSE
EXEC SP_HELP [@GSP_TPVWCD]
SELECT U_GSP_FILWAREHOUSE, U_GSP_AUTOEXEC, U_GSP_FILDATEEND FROM [@GSP_TPVWCD] WHERE U_GSP_FILWAREHOUSE='111'




SELECT U_GSP_FILWAREHOUSE, U_GSP_NAME, U_GSP_DESC FROM [@GSP_TPVWCD] order by U_GSP_FILWAREHOUSE
SELECT * FROM OWHS WHERE U_GSP_SENDTPV='Y'
SELECT U_GSP_SHOP, U_GSP_DFLTCARD FROM [@GSP_TPVSHOP] order by U_GSP_SHOP




SELECT U_GSP_DFLTCARD, U_GSP_TIPOINTEGR, U_GSP_TIPOINTEGRCP FROM [@GSP_TPVSHOP]
SELECT U_GSP_DFLTCARD,U_GSP_TIPOINTEGR, U_GSP_TIPOINTEGRCP FROM [@GSP_TPVSHOP] WHERE U_GSP_SHOP='111'
--update [@GSP_TPVSHOP] set U_GSP_TIPOINTEGR='FACT+COBRO', U_GSP_TIPOINTEGRCP='INTEGRAR'  WHERE U_GSP_SHOP='111'
--update [@GSP_TPVSHOP] set U_GSP_TIPOINTEGR='NO_INTEG', U_GSP_TIPOINTEGRCP='NO_INTEG' WHERE U_GSP_SHOP='111'
EXEC SP_HELP [@GSP_TPVSHOP] 
EXEC sp_columns [@GSP_TPVSHOP] 

/**********************update checkbox en el server 192.168.0.33********************************************/

--update [@GSP_TPVSHOP] set U_GSP_TIPOINTEGR='NO_INTEG', U_GSP_TIPOINTEGRCP='NO_INTEG' WHERE U_GSP_SHOP= '${codStore}   /*sin check ROJO*/

--update [@GSP_TPVSHOP] set U_GSP_TIPOINTEGR='FACT+COBRO', U_GSP_TIPOINTEGRCP='INTEGRAR'  WHERE U_GSP_SHOP= '${codStore}'   /*con check VERDE*/

--update [@GSP_TPVWCD] set U_GSP_AUTOEXEC='N', U_GSP_FILDATEEND=getdate()-1 WHERE U_GSP_FILWAREHOUSE='${codStore}'                  /*sin check ROJO*/

--update [@GSP_TPVWCD] set U_GSP_AUTOEXEC='Y', U_GSP_FILDATEEND='2099-12-31' WHERE U_GSP_FILWAREHOUSE='${codStore}'                       /*con check VERDE*/

SELECT T1.U_GSP_DFLTCARD, T1.U_GSP_TIPOINTEGR, T1.U_GSP_TIPOINTEGRCP, T2.U_GSP_AUTOEXEC, T2.U_GSP_AUTOEXEC FROM [@GSP_TPVSHOP] AS T1 INNER JOIN [@GSP_TPVWCD] AS T2   ON T1.U_GSP_DFLTCARD=T2.U_GSP_NAME

